// example/svelte-in-different-dir/frontend/src/App.svelte
<script lang="ts">
    let count = $state(0)
</script>

<main>
    <h1>Django + Vite + Svelte</h1>
    <p>
        Served by Django from <code>templates/index.html</code>; everything
        else on this page comes from the <code>frontend/</code> directory.
    </p>
    <button onclick={() => count++}>
        Count: {count}
    </button>
    <p class="hint">
        Edit <code>frontend/src/App.svelte</code> — HMR keeps the count.
    </p>
</main>

<style>
    main {
        max-width: 32rem;
        margin: 4rem auto;
        text-align: center;
    }

    button {
        font-size: 1.25rem;
        padding: 0.5rem 1.5rem;
        cursor: pointer;
    }

    .hint {
        color: #64748b;
        font-size: 0.875rem;
    }
</style>

// example/react/ui/templates/ui/App.tsx
// This component lives in the app's templates/ directory to demonstrate the
// `@t:ui` alias — see ui/static/ui/js/main.tsx for the import.
import { useState } from 'react'

const styles: Record<string, React.CSSProperties> = {
    main: {
        fontFamily: 'system-ui, sans-serif',
        maxWidth: '32rem',
        margin: '4rem auto',
        textAlign: 'center',
    },
    button: {
        fontSize: '1.25rem',
        padding: '0.5rem 1.5rem',
        cursor: 'pointer',
    },
}

export default function App() {
    const [count, setCount] = useState(0)

    return (
        <main style={styles.main}>
            <h1>Django + Vite + React</h1>
            <p>
                Served by Django, bundled by Vite. Edit this component and the
                counter below keeps its state thanks to Fast Refresh.
            </p>
            <button style={styles.button} onClick={() => setCount(count + 1)}>
                Count: {count}
            </button>
        </main>
    )
}
